# GENERAL SETTINGS
window:
  padding:
    x: 15
    y: 10
  dynamic_padding: false
  dynamic_title: true
  title: Terminal
font:
  normal:
    family: Iosevka
    style: Normal
  italic:
    family: Iosevka
    style: Italic
  bold:
    family: Iosevka
    style: Bold
  size: 15
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
scrolling:
  history: 5000
  multiplier: 3
mouse:
  hide_when_typing: true
cursor:
  style:
    shape: Block
  unfocused_hollow: true
selection:
  save_to_clipboard: true
debug:
  persistent_logging: true
logging: true
draw_bold_text_with_bright_colors: true
background_opacity: 0.92

base16_colors:
  base00: &base00 "#161616"
  base01: &base01 "#262626"
  base02: &base02 "#393939"
  base03: &base03 "#525252"
  base04: &base04 "#dde1e6"
  base05: &base05 "#f2f4f8"
  base06: &base06 "#ffffff"
  base07: &base07 "#08bdba"
  base08: &base08 "#3ddbd9"
  base09: &base09 "#78a9ff"
  base0A: &base0A "#ee5396"
  base0B: &base0B "#33b1ff"
  base0C: &base0C "#ff7eb6"
  base0D: &base0D "#42be65"
  base0E: &base0E "#be95ff"
  base0F: &base0F "#82cfff"

colors:
  primary:
    background: *base00
    foreground: *base06

  normal:
    black:   *base00
    red:     *base0B
    green:   *base0C
    yellow:  *base0D
    blue:    *base07
    magenta: *base0E
    cyan:    *base09
    white:   *base04

  bright:
    black:   *base03
    red:     *base0B
    green:   *base0C
    yellow:  *base0D
    blue:    *base08
    magenta: *base0F
    cyan:    *base09
    white:   *base06
